<a href="https://colab.research.google.com/github/AnushkaMishra29/Churning-Model/blob/master/Churning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [0]:
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [0]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [9]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [0]:
ann=tf.keras.models.Sequential()

In [0]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


In [0]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [16]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5861 - accuracy: 0.7143
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4750 - accuracy: 0.8065
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4476 - accuracy: 0.8091
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4385 - accuracy: 0.8095
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8127
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4262 - accuracy: 0.8150
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4233 - accuracy: 0.8175
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4201 - accuracy: 0.8183
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4164 - accura

In [20]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [21]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [23]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1523   72]
 [ 205  200]]


0.8615